### ISSUE TITLE
Significant visual issues with nameplates

### ISSUE THREAD

**Issue by forever-and-a-day** [markviews/FriendNotes#2]
Nameplate text appears very dim and in some situations (like when one nameplate is in front of another) nameplate text is not visible at all. 
Image attached for demonstration. Also logs. 
[Latest.log](https://github.com/markviews/FriendNotes/files/7104090/Latest.log)
![20210902203422_1](https://user-images.githubusercontent.com/10383240/131965365-ebfb4227-3ac4-49d7-bcac-dbea36e89b13.jpg)

**Comment by markviews** [comment]
I am very confused by this, my mod does not touch opacity. I'll look into it tho

**Comment by markviews** [comment]
i'm guessing it's one of your other mods. I don't have time right now but i'll try to figure out which one in a bit

**Comment by markviews** [comment]
I haven't been able to re-produce this exact result but I think update 1.0.8 should fix this.

**Comment by forever-and-a-day** [comment]
Okay! Thanks for looking into it! Sorry if I was mistaken lol
